/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Market {
  'resolutionDate' : Time,
  'status' : { 'resolved' : null } |
    { 'active' : null } |
    { 'pending' : null },
  'creator' : Principal,
  'question' : string,
  'description' : string,
  'volume' : bigint,
  'marketId' : bigint,
  'noPrice' : number,
  'category' : MarketCategory,
  'yesPrice' : number,
}
export type MarketCategory = { 'entertainment' : null } |
  { 'crypto' : null } |
  { 'technology' : null } |
  { 'sports' : null } |
  { 'politics' : null };
export interface Order {
  'user' : Principal,
  'orderType' : OrderType,
  'orderId' : bigint,
  'marketId' : bigint,
  'timestamp' : Time,
  'quantity' : bigint,
  'shareType' : { 'no' : null } |
    { 'yes' : null },
  'price' : number,
}
export type OrderType = { 'buy' : null } |
  { 'sell' : null };
export interface Position {
  'pnl' : number,
  'avgPrice' : number,
  'marketId' : bigint,
  'quantity' : bigint,
  'shareType' : { 'no' : null } |
    { 'yes' : null },
}
export interface Reward {
  'streak' : bigint,
  'weeklyChallenge' : bigint,
  'earlyPredictor' : bigint,
  'user' : Principal,
  'referrals' : bigint,
  'totalPoints' : bigint,
}
export type Time = bigint;
export interface Trade {
  'seller' : Principal,
  'orderId' : bigint,
  'tradeId' : bigint,
  'marketId' : bigint,
  'timestamp' : Time,
  'quantity' : bigint,
  'buyer' : Principal,
  'price' : number,
}
export interface UserProfile {
  'pnl' : number,
  'totalTrades' : bigint,
  'username' : string,
  'tier' : { 'bronze' : null } |
    { 'gold' : null } |
    { 'elite' : null } |
    { 'silver' : null },
  'reputation' : bigint,
  'winRate' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], undefined>,
  'claimRewards' : ActorMethod<[], undefined>,
  /**
   * / ************* MARKETS **************
   */
  'createMarket' : ActorMethod<[string, string, MarketCategory, Time], bigint>,
  'createProfile' : ActorMethod<[string], undefined>,
  'getActiveMarkets' : ActorMethod<[], Array<Market>>,
  'getAllMarkets' : ActorMethod<[], Array<Market>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarket' : ActorMethod<[bigint], Market>,
  'getMarketsByCategory' : ActorMethod<[MarketCategory], Array<Market>>,
  'getMarketsByCreator' : ActorMethod<[Principal], Array<Market>>,
  'getOrderBook' : ActorMethod<[bigint], Array<Order>>,
  'getTopRewardUsers' : ActorMethod<[], Array<Reward>>,
  'getTopUsersByPnl' : ActorMethod<[], Array<UserProfile>>,
  'getTopUsersByReputation' : ActorMethod<[], Array<UserProfile>>,
  'getTopUsersByWinRate' : ActorMethod<[], Array<UserProfile>>,
  'getTradeHistory' : ActorMethod<[bigint], Array<Trade>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  /**
   * / ************* POSITIONS **************
   */
  'getUserPositions' : ActorMethod<[Principal], Array<Position>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / ************* REWARDS **************
   */
  'getUserRewards' : ActorMethod<[Principal], [] | [Reward]>,
  'getUserTrades' : ActorMethod<[Principal], Array<Trade>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / ************* USERS/PROFILES **************
   */
  'isUsernameTaken' : ActorMethod<[string], boolean>,
  /**
   * / ************* TRADING **************
   */
  'placeOrder' : ActorMethod<
    [bigint, OrderType, { 'no' : null } | { 'yes' : null }, number, bigint],
    bigint
  >,
  /**
   * / ************* MARKET RESOLUTION (ADMIN ONLY) **************
   */
  'resolveMarket' : ActorMethod<
    [bigint, { 'no' : null } | { 'yes' : null }],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMarketStatus' : ActorMethod<
    [
      bigint,
      { 'resolved' : null } |
        { 'active' : null } |
        { 'pending' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];