/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MarketCategory = IDL.Variant({
  'entertainment' : IDL.Null,
  'crypto' : IDL.Null,
  'technology' : IDL.Null,
  'sports' : IDL.Null,
  'politics' : IDL.Null,
});
export const Time = IDL.Int;
export const Market = IDL.Record({
  'resolutionDate' : Time,
  'status' : IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
  }),
  'creator' : IDL.Principal,
  'question' : IDL.Text,
  'description' : IDL.Text,
  'volume' : IDL.Nat,
  'marketId' : IDL.Nat,
  'noPrice' : IDL.Float64,
  'category' : MarketCategory,
  'yesPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'pnl' : IDL.Float64,
  'totalTrades' : IDL.Nat,
  'username' : IDL.Text,
  'tier' : IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'elite' : IDL.Null,
    'silver' : IDL.Null,
  }),
  'reputation' : IDL.Nat,
  'winRate' : IDL.Float64,
});
export const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Order = IDL.Record({
  'user' : IDL.Principal,
  'orderType' : OrderType,
  'orderId' : IDL.Nat,
  'marketId' : IDL.Nat,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'shareType' : IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null }),
  'price' : IDL.Float64,
});
export const Reward = IDL.Record({
  'streak' : IDL.Nat,
  'weeklyChallenge' : IDL.Nat,
  'earlyPredictor' : IDL.Nat,
  'user' : IDL.Principal,
  'referrals' : IDL.Nat,
  'totalPoints' : IDL.Nat,
});
export const Trade = IDL.Record({
  'seller' : IDL.Principal,
  'orderId' : IDL.Nat,
  'tradeId' : IDL.Nat,
  'marketId' : IDL.Nat,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'buyer' : IDL.Principal,
  'price' : IDL.Float64,
});
export const Position = IDL.Record({
  'pnl' : IDL.Float64,
  'avgPrice' : IDL.Float64,
  'marketId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'shareType' : IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [], []),
  'claimRewards' : IDL.Func([], [], []),
  'createMarket' : IDL.Func(
      [IDL.Text, IDL.Text, MarketCategory, Time],
      [IDL.Nat],
      [],
    ),
  'createProfile' : IDL.Func([IDL.Text], [], []),
  'getActiveMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
  'getAllMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMarket' : IDL.Func([IDL.Nat], [Market], ['query']),
  'getMarketsByCategory' : IDL.Func(
      [MarketCategory],
      [IDL.Vec(Market)],
      ['query'],
    ),
  'getMarketsByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Market)],
      ['query'],
    ),
  'getOrderBook' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getTopRewardUsers' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getTopUsersByPnl' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTopUsersByReputation' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTopUsersByWinRate' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTradeHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserPositions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Position)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRewards' : IDL.Func([IDL.Principal], [IDL.Opt(Reward)], ['query']),
  'getUserTrades' : IDL.Func([IDL.Principal], [IDL.Vec(Trade)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Nat,
        OrderType,
        IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null }),
        IDL.Float64,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'resolveMarket' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null })],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMarketStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'resolved' : IDL.Null,
          'active' : IDL.Null,
          'pending' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MarketCategory = IDL.Variant({
    'entertainment' : IDL.Null,
    'crypto' : IDL.Null,
    'technology' : IDL.Null,
    'sports' : IDL.Null,
    'politics' : IDL.Null,
  });
  const Time = IDL.Int;
  const Market = IDL.Record({
    'resolutionDate' : Time,
    'status' : IDL.Variant({
      'resolved' : IDL.Null,
      'active' : IDL.Null,
      'pending' : IDL.Null,
    }),
    'creator' : IDL.Principal,
    'question' : IDL.Text,
    'description' : IDL.Text,
    'volume' : IDL.Nat,
    'marketId' : IDL.Nat,
    'noPrice' : IDL.Float64,
    'category' : MarketCategory,
    'yesPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'pnl' : IDL.Float64,
    'totalTrades' : IDL.Nat,
    'username' : IDL.Text,
    'tier' : IDL.Variant({
      'bronze' : IDL.Null,
      'gold' : IDL.Null,
      'elite' : IDL.Null,
      'silver' : IDL.Null,
    }),
    'reputation' : IDL.Nat,
    'winRate' : IDL.Float64,
  });
  const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Order = IDL.Record({
    'user' : IDL.Principal,
    'orderType' : OrderType,
    'orderId' : IDL.Nat,
    'marketId' : IDL.Nat,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'shareType' : IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null }),
    'price' : IDL.Float64,
  });
  const Reward = IDL.Record({
    'streak' : IDL.Nat,
    'weeklyChallenge' : IDL.Nat,
    'earlyPredictor' : IDL.Nat,
    'user' : IDL.Principal,
    'referrals' : IDL.Nat,
    'totalPoints' : IDL.Nat,
  });
  const Trade = IDL.Record({
    'seller' : IDL.Principal,
    'orderId' : IDL.Nat,
    'tradeId' : IDL.Nat,
    'marketId' : IDL.Nat,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'buyer' : IDL.Principal,
    'price' : IDL.Float64,
  });
  const Position = IDL.Record({
    'pnl' : IDL.Float64,
    'avgPrice' : IDL.Float64,
    'marketId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'shareType' : IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [], []),
    'claimRewards' : IDL.Func([], [], []),
    'createMarket' : IDL.Func(
        [IDL.Text, IDL.Text, MarketCategory, Time],
        [IDL.Nat],
        [],
      ),
    'createProfile' : IDL.Func([IDL.Text], [], []),
    'getActiveMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
    'getAllMarkets' : IDL.Func([], [IDL.Vec(Market)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMarket' : IDL.Func([IDL.Nat], [Market], ['query']),
    'getMarketsByCategory' : IDL.Func(
        [MarketCategory],
        [IDL.Vec(Market)],
        ['query'],
      ),
    'getMarketsByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Market)],
        ['query'],
      ),
    'getOrderBook' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getTopRewardUsers' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getTopUsersByPnl' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTopUsersByReputation' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTopUsersByWinRate' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTradeHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserPositions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Position)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRewards' : IDL.Func([IDL.Principal], [IDL.Opt(Reward)], ['query']),
    'getUserTrades' : IDL.Func([IDL.Principal], [IDL.Vec(Trade)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Nat,
          OrderType,
          IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null }),
          IDL.Float64,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'resolveMarket' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'no' : IDL.Null, 'yes' : IDL.Null })],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMarketStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'resolved' : IDL.Null,
            'active' : IDL.Null,
            'pending' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };