/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Reward {
    streak: bigint;
    weeklyChallenge: bigint;
    earlyPredictor: bigint;
    user: Principal;
    referrals: bigint;
    totalPoints: bigint;
}
export interface Position {
    pnl: number;
    avgPrice: number;
    marketId: bigint;
    quantity: bigint;
    shareType: Variant_no_yes;
}
export interface Trade {
    seller: Principal;
    orderId: bigint;
    tradeId: bigint;
    marketId: bigint;
    timestamp: Time;
    quantity: bigint;
    buyer: Principal;
    price: number;
}
export interface Market {
    resolutionDate: Time;
    status: Variant_resolved_active_pending;
    creator: Principal;
    question: string;
    description: string;
    volume: bigint;
    marketId: bigint;
    noPrice: number;
    category: MarketCategory;
    yesPrice: number;
}
export interface Order {
    user: Principal;
    orderType: OrderType;
    orderId: bigint;
    marketId: bigint;
    timestamp: Time;
    quantity: bigint;
    shareType: Variant_no_yes;
    price: number;
}
export interface UserProfile {
    pnl: number;
    totalTrades: bigint;
    username: string;
    tier: Variant_bronze_gold_elite_silver;
    reputation: bigint;
    winRate: number;
}
export enum MarketCategory {
    entertainment = "entertainment",
    crypto = "crypto",
    technology = "technology",
    sports = "sports",
    politics = "politics"
}
export enum OrderType {
    buy = "buy",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_bronze_gold_elite_silver {
    bronze = "bronze",
    gold = "gold",
    elite = "elite",
    silver = "silver"
}
export enum Variant_no_yes {
    no = "no",
    yes = "yes"
}
export enum Variant_resolved_active_pending {
    resolved = "resolved",
    active = "active",
    pending = "pending"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelOrder(orderId: bigint): Promise<void>;
    claimRewards(): Promise<void>;
    /**
     * / ************* MARKETS **************
     */
    createMarket(question: string, description: string, category: MarketCategory, resolutionDate: Time): Promise<bigint>;
    createProfile(username: string): Promise<void>;
    getActiveMarkets(): Promise<Array<Market>>;
    getAllMarkets(): Promise<Array<Market>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMarket(marketId: bigint): Promise<Market>;
    getMarketsByCategory(category: MarketCategory): Promise<Array<Market>>;
    getMarketsByCreator(creator: Principal): Promise<Array<Market>>;
    getOrderBook(marketId: bigint): Promise<Array<Order>>;
    getTopRewardUsers(): Promise<Array<Reward>>;
    getTopUsersByPnl(): Promise<Array<UserProfile>>;
    getTopUsersByReputation(): Promise<Array<UserProfile>>;
    getTopUsersByWinRate(): Promise<Array<UserProfile>>;
    getTradeHistory(marketId: bigint): Promise<Array<Trade>>;
    getUserOrders(user: Principal): Promise<Array<Order>>;
    /**
     * / ************* POSITIONS **************
     */
    getUserPositions(user: Principal): Promise<Array<Position>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / ************* REWARDS **************
     */
    getUserRewards(user: Principal): Promise<Reward | null>;
    getUserTrades(user: Principal): Promise<Array<Trade>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / ************* USERS/PROFILES **************
     */
    isUsernameTaken(username: string): Promise<boolean>;
    /**
     * / ************* TRADING **************
     */
    placeOrder(marketId: bigint, orderType: OrderType, shareType: Variant_no_yes, price: number, quantity: bigint): Promise<bigint>;
    /**
     * / ************* MARKET RESOLUTION (ADMIN ONLY) **************
     */
    resolveMarket(marketId: bigint, outcome: Variant_no_yes): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMarketStatus(marketId: bigint, status: Variant_resolved_active_pending): Promise<void>;
}
import type { Market as _Market, MarketCategory as _MarketCategory, Order as _Order, OrderType as _OrderType, Position as _Position, Reward as _Reward, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async claimRewards(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimRewards();
            return result;
        }
    }
    async createMarket(arg0: string, arg1: string, arg2: MarketCategory, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarket(arg0, arg1, to_candid_MarketCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarket(arg0, arg1, to_candid_MarketCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0);
            return result;
        }
    }
    async getActiveMarkets(): Promise<Array<Market>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveMarkets();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveMarkets();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMarkets(): Promise<Array<Market>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarkets();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarkets();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarket(arg0: bigint): Promise<Market> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarket(arg0);
                return from_candid_Market_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarket(arg0);
            return from_candid_Market_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketsByCategory(arg0: MarketCategory): Promise<Array<Market>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketsByCategory(to_candid_MarketCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketsByCategory(to_candid_MarketCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketsByCreator(arg0: Principal): Promise<Array<Market>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketsByCreator(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketsByCreator(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderBook(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderBook(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderBook(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopRewardUsers(): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopRewardUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopRewardUsers();
            return result;
        }
    }
    async getTopUsersByPnl(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUsersByPnl();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUsersByPnl();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopUsersByReputation(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUsersByReputation();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUsersByReputation();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopUsersByWinRate(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUsersByWinRate();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUsersByWinRate();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeHistory(arg0: bigint): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeHistory(arg0);
            return result;
        }
    }
    async getUserOrders(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPositions(arg0: Principal): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPositions(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPositions(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRewards(arg0: Principal): Promise<Reward | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRewards(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRewards(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTrades(arg0: Principal): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTrades(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTrades(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUsernameTaken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameTaken(arg0);
            return result;
        }
    }
    async placeOrder(arg0: bigint, arg1: OrderType, arg2: Variant_no_yes, arg3: number, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, to_candid_OrderType_n28(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n30(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, to_candid_OrderType_n28(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n30(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async resolveMarket(arg0: bigint, arg1: Variant_no_yes): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveMarket(arg0, to_candid_variant_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveMarket(arg0, to_candid_variant_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMarketStatus(arg0: bigint, arg1: Variant_resolved_active_pending): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_MarketCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketCategory): MarketCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Market_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Market): Market {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Reward]): Reward | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pnl: number;
    totalTrades: bigint;
    username: string;
    tier: {
        bronze: null;
    } | {
        gold: null;
    } | {
        elite: null;
    } | {
        silver: null;
    };
    reputation: bigint;
    winRate: number;
}): {
    pnl: number;
    totalTrades: bigint;
    username: string;
    tier: Variant_bronze_gold_elite_silver;
    reputation: bigint;
    winRate: number;
} {
    return {
        pnl: value.pnl,
        totalTrades: value.totalTrades,
        username: value.username,
        tier: from_candid_variant_n14(_uploadFile, _downloadFile, value.tier),
        reputation: value.reputation,
        winRate: value.winRate
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    orderType: _OrderType;
    orderId: bigint;
    marketId: bigint;
    timestamp: _Time;
    quantity: bigint;
    shareType: {
        no: null;
    } | {
        yes: null;
    };
    price: number;
}): {
    user: Principal;
    orderType: OrderType;
    orderId: bigint;
    marketId: bigint;
    timestamp: Time;
    quantity: bigint;
    shareType: Variant_no_yes;
    price: number;
} {
    return {
        user: value.user,
        orderType: from_candid_OrderType_n20(_uploadFile, _downloadFile, value.orderType),
        orderId: value.orderId,
        marketId: value.marketId,
        timestamp: value.timestamp,
        quantity: value.quantity,
        shareType: from_candid_variant_n22(_uploadFile, _downloadFile, value.shareType),
        price: value.price
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pnl: number;
    avgPrice: number;
    marketId: bigint;
    quantity: bigint;
    shareType: {
        no: null;
    } | {
        yes: null;
    };
}): {
    pnl: number;
    avgPrice: number;
    marketId: bigint;
    quantity: bigint;
    shareType: Variant_no_yes;
} {
    return {
        pnl: value.pnl,
        avgPrice: value.avgPrice,
        marketId: value.marketId,
        quantity: value.quantity,
        shareType: from_candid_variant_n22(_uploadFile, _downloadFile, value.shareType)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolutionDate: _Time;
    status: {
        resolved: null;
    } | {
        active: null;
    } | {
        pending: null;
    };
    creator: Principal;
    question: string;
    description: string;
    volume: bigint;
    marketId: bigint;
    noPrice: number;
    category: _MarketCategory;
    yesPrice: number;
}): {
    resolutionDate: Time;
    status: Variant_resolved_active_pending;
    creator: Principal;
    question: string;
    description: string;
    volume: bigint;
    marketId: bigint;
    noPrice: number;
    category: MarketCategory;
    yesPrice: number;
} {
    return {
        resolutionDate: value.resolutionDate,
        status: from_candid_variant_n8(_uploadFile, _downloadFile, value.status),
        creator: value.creator,
        question: value.question,
        description: value.description,
        volume: value.volume,
        marketId: value.marketId,
        noPrice: value.noPrice,
        category: from_candid_MarketCategory_n9(_uploadFile, _downloadFile, value.category),
        yesPrice: value.yesPrice
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entertainment: null;
} | {
    crypto: null;
} | {
    technology: null;
} | {
    sports: null;
} | {
    politics: null;
}): MarketCategory {
    return "entertainment" in value ? MarketCategory.entertainment : "crypto" in value ? MarketCategory.crypto : "technology" in value ? MarketCategory.technology : "sports" in value ? MarketCategory.sports : "politics" in value ? MarketCategory.politics : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    elite: null;
} | {
    silver: null;
}): Variant_bronze_gold_elite_silver {
    return "bronze" in value ? Variant_bronze_gold_elite_silver.bronze : "gold" in value ? Variant_bronze_gold_elite_silver.gold : "elite" in value ? Variant_bronze_gold_elite_silver.elite : "silver" in value ? Variant_bronze_gold_elite_silver.silver : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): OrderType {
    return "buy" in value ? OrderType.buy : "sell" in value ? OrderType.sell : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    no: null;
} | {
    yes: null;
}): Variant_no_yes {
    return "no" in value ? Variant_no_yes.no : "yes" in value ? Variant_no_yes.yes : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    active: null;
} | {
    pending: null;
}): Variant_resolved_active_pending {
    return "resolved" in value ? Variant_resolved_active_pending.resolved : "active" in value ? Variant_resolved_active_pending.active : "pending" in value ? Variant_resolved_active_pending.pending : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Position>): Array<Position> {
    return value.map((x)=>from_candid_Position_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Market>): Array<Market> {
    return value.map((x)=>from_candid_Market_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MarketCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketCategory): _MarketCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pnl: number;
    totalTrades: bigint;
    username: string;
    tier: Variant_bronze_gold_elite_silver;
    reputation: bigint;
    winRate: number;
}): {
    pnl: number;
    totalTrades: bigint;
    username: string;
    tier: {
        bronze: null;
    } | {
        gold: null;
    } | {
        elite: null;
    } | {
        silver: null;
    };
    reputation: bigint;
    winRate: number;
} {
    return {
        pnl: value.pnl,
        totalTrades: value.totalTrades,
        username: value.username,
        tier: to_candid_variant_n33(_uploadFile, _downloadFile, value.tier),
        reputation: value.reputation,
        winRate: value.winRate
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    buy: null;
} | {
    sell: null;
} {
    return value == OrderType.buy ? {
        buy: null
    } : value == OrderType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_no_yes): {
    no: null;
} | {
    yes: null;
} {
    return value == Variant_no_yes.no ? {
        no: null
    } : value == Variant_no_yes.yes ? {
        yes: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_bronze_gold_elite_silver): {
    bronze: null;
} | {
    gold: null;
} | {
    elite: null;
} | {
    silver: null;
} {
    return value == Variant_bronze_gold_elite_silver.bronze ? {
        bronze: null
    } : value == Variant_bronze_gold_elite_silver.gold ? {
        gold: null
    } : value == Variant_bronze_gold_elite_silver.elite ? {
        elite: null
    } : value == Variant_bronze_gold_elite_silver.silver ? {
        silver: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_resolved_active_pending): {
    resolved: null;
} | {
    active: null;
} | {
    pending: null;
} {
    return value == Variant_resolved_active_pending.resolved ? {
        resolved: null
    } : value == Variant_resolved_active_pending.active ? {
        active: null
    } : value == Variant_resolved_active_pending.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketCategory): {
    entertainment: null;
} | {
    crypto: null;
} | {
    technology: null;
} | {
    sports: null;
} | {
    politics: null;
} {
    return value == MarketCategory.entertainment ? {
        entertainment: null
    } : value == MarketCategory.crypto ? {
        crypto: null
    } : value == MarketCategory.technology ? {
        technology: null
    } : value == MarketCategory.sports ? {
        sports: null
    } : value == MarketCategory.politics ? {
        politics: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
